import './globals.css'
import Header from '@/components/header/Header'
import CategoryMenu from '@/components/CategoryMenu'
import Footer from '@/components/footer/Footer'
import { MyContextProvider } from '@/contexts/MyContextProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <meta name="theme-color" content="#cdcecf" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </head>
      <MyContextProvider>
        <body className='bg-[#f0f9ff]'>
          <Header />
          <CategoryMenu />
          {children}
          <Footer />
        </body>
      </MyContextProvider>
    </html>
  )
}
